### ISSUE TITLE
Data wasn't updated since 2019-02-05

### ISSUE THREAD

**Issue by anuveyatsu** [datasets/co2-ppm-daily#5]
On https://datahub.io/core/co2-ppm-daily if you check the latest data, it is for 2019-02-05, however, it says it is updated a few hours ago.

**Comment by RJBethune** [comment]
Any update on this issue?

**Comment by svetozarstojkovic** [comment]
The problem that occurred here is that Travis CI doesn't support FTP requests. - [source](https://docs.travis-ci.com/user/common-build-problems/#ftpsmtpother-protocol-does-not-work)

Now I changed a logic because ftp request was reading old data which I now stored in data/co2-ppm-daily.csv. That file now as default has values until end of 2017 and all data after it is being appended to same file and deployed to datahub as the newest version.

Please test and see if everything is in order.
